<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-07-21 11:01

$extensionPath = t3lib_extMgm::extPath('ics_tcafe_admin');
return array(
	'tx_icstcafeadmin_display' => $extensionPath . 'lib/class.tx_icstcafeadmin_display.php',
	'tx_icstcafeadmin_dynflex' => $extensionPath . 'lib/class.tx_icstcafeadmin_dynflex.php',
	'tx_icstcafeadmin_pi1' => $extensionPath . 'pi1/class.tx_icstcafeadmin_pi1.php',
	'tx_icstcafeadmin_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icstcafeadmin_pi1_wizicon.php',
);
?>