<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-04-20 15:18

$extensionPath = t3lib_extMgm::extPath('ics_tcafe_admin');
return array(
	'tx_icstcafeadmin_display' => $extensionPath . 'class.tx_icstcafeadmin_display.php',
	'tx_icstcafeadmin_debug' => $extensionPath . 'Classes/class.tx_icstcafeadmin_debug.php',
	'tx_icstcafeadmin_dynflex' => $extensionPath . 'Classes/class.tx_icstcafeadmin_dynflex.php',
	'tx_icstcafeadmin_dbtools' => $extensionPath . 'Classes/data/class.tx_icstcafeadmin_DBTools.php',
	'tx_icstcafeadmin_controlform' => $extensionPath . 'Classes/data/class.tx_icstcafeadmin_controlForm.php',
	'tx_icstcafeadmin_commonrenderer' => $extensionPath . 'Classes/renderer/class.tx_icstcafeadmin_CommonRenderer.php',
	'tx_icstcafeadmin_formrenderer' => $extensionPath . 'Classes/renderer/class.tx_icstcafeadmin_FormRenderer.php',
	'tx_icstcafeadmin_listrenderer' => $extensionPath . 'Classes/renderer/class.tx_icstcafeadmin_ListRenderer.php',
	'tx_icstcafeadmin_singlerenderer' => $extensionPath . 'Classes/renderer/class.tx_icstcafeadmin_SingleRenderer.php',
	'tx_icstcafeadmin_pi1' => $extensionPath . 'pi1/class.tx_icstcafeadmin_pi1.php',
	'tx_icstcafeadmin_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icstcafeadmin_pi1_wizicon.php',
);
?>